name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}
    stratagy:
      matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 1.8

    - name: grant execute permission for gradlew
      uses: chmod +x gradflew
      
    - name: build with gradle
      run: ./gradlew build

  publish:

      needs: build
